### ISSUE TITLE
Aether forkbombing the backend

### ISSUE THREAD

**Issue by redblade7** [Frigyes06/aether-app#56]
I've been using Aether for a while, but as of yesterday, Aether keeps launching aether-backend-linux-x64 over and over with a different port each time.

When running from the terminal, I noticed this repeating error message, which claims the frontend is being relaunched but it is actually the backend that is being relaunched:

```
panic: runtime error: index out of range [0] with length 0

goroutine 82 [running]:
aether-core/aether/frontend/refresher.DeleteStaleData(0xc00007f060?)
	/home/frigyes/aether-app/aether-core/aether/frontend/refresher/refresher.go:121 +0x7e5
aether-core/aether/frontend/refresher.Refresh()
	/home/frigyes/aether-app/aether-core/aether/frontend/refresher/refresher.go:80 +0x45c
aether-core/aether/frontend/fecmd.startSchedules.func1()
	/home/frigyes/aether-app/aether-core/aether/frontend/fecmd/run.go:130 +0x31
aether-core/aether/services/scheduling.ScheduleRepeat.func1()
	/home/frigyes/aether-app/aether-core/aether/services/scheduling/scheduling.go:35 +0xa5
created by aether-core/aether/services/scheduling.ScheduleRepeat
	/home/frigyes/aether-app/aether-core/aether/services/scheduling/scheduling.go:21 +0xfa

Frontend process exited with code 2 and signal null
We will reattempt to start the frontend daemon in 10 seconds.
```

**Comment by Frigyes06** [comment]
That is weird...

Is it reproducible?

**Comment by voxnyx** [comment]
@redblade7 Is this a reoccurring thing? I have not experienced this issue.

**Comment by Julian-1-2-3-4-5** [comment]
> @redblade7 Is this a reoccurring thing? I have not experienced this issue.

I aswell haven't had this issue

**Comment by redblade7** [comment]
I managed to get into the app by deleting everything in $HOME/.config/Air Labs/Aether/frontend/ except for frontend_config.json. However, I have no posts past December 2023 now, excluding a test post I just made to b/Meta.
